name: Build Package
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"]
  release:
    types: [published]

jobs:
  publish-test:
    name: Test Package Build and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          twine
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --outdir dist/

      - name: Twine PyPi checks
        run: twine check dist/*

      - name: Install and Check Package Wheel
        run: pip install ./dist/*.whl && python -c "import lai_textpred; print(lai_textpred.__version__)"

      - name: Install and Check Package Source Distribution
        run: pip install ./dist/*.tar.gz --force-reinstall && python -c "import lai_textpred; print(lai_textpred.__version__)"